### ISSUE TITLE
dynamic boundaries

### ISSUE THREAD

**Issue by Yoorthiziri** [pylbm/pylbm#108]
Hello,
Thank you very much for this project. 
I have a question regarding dynamic boundaries in pylbm. Is it possible to do a simulation with a moving boundary condition, I mean for example:

* Flow around an oscillating cylinder.
* Flow around a rotating object.
* a flow in 2D around an object where the top boundary is moving(changing y coordinates specified by a function)...etc

Thank you

**Comment by gouarin** [comment]
hello @Yoorthiziri,
thank you for your interest.

There is no implementation of dynamic boundaries at the moment in pylbm. But it should not be so difficult to add this feature. We just need to add an interpolation operator to compute the distribution functions in the new fluid cells and to recompute the distance of the fluid cells and the different obstacles.

I don't have a lot of time these days but I can think about it in January.

**Comment by Yoorthiziri** [comment]
Thank you very much for your answer.
I am looking forward to see this feature implemented in `pylbm`.

**Comment by mullaengr** [comment]
Hello
I am facing a problem while running pylbm on my system. Please guide me where is the problem.
Thanks in advance.
here is the error message.

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by gouarin** [comment]
@Yoorthiziri The dynamic boundary conditions are now implemented (see https://github.com/pylbm/pylbm/issues/127)
