### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mullaengr** [pylbm/pylbm#113]
Hello 
I am facing a problem while running pylbm on my system. Please guide me where is the problem.
Thanks in advance.
here is the error message.

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by gouarin** [comment]
@mullaengr we need more information in order to help you with the installation of pylbm.

How did you install pylbm? By using `pip`?

It seems that you are on Windows. Did you install:

- https://visualstudio.microsoft.com/free-developer-offers/
- https://www.microsoft.com/en-us/download/details.aspx?id=57467

And please send us the whole error message.

**Comment by mullaengr** [comment]
Thank you for your reply.Yes, I am using windows 10 and I have installed pylbm py using pip.
here is the error message:

Traceback (most recent call last):
  File "D:/Python practice/py_LBM/LBM_2d.py", line 1, in <module>
    import pylbm
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\pylbm\__init__.py", line 12, in <module>
    import mpi4py.MPI as mpi
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by mullaengr** [comment]
I have installed the Microsoft MPI v10.0 but the code showing same message.
I have Microsoft Visual Studio installed already.

waiting for your reply.

Thank you

**Comment by gouarin** [comment]
Could you try to reinstall `mpi4py`?

**Comment by mullaengr** [comment]
I have done it but showing same error message :(

**Comment by mullaengr** [comment]
Traceback (most recent call last):
  File "D:/Python practice/py_LBM/LBM_2d.py", line 1, in <module>
    import pylbm
  File "C:\Users\Ali\AppData\Roaming\Python\Python37\site-packages\pylbm\__init__.py", line 12, in <module>
    import mpi4py.MPI as mpi
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by gouarin** [comment]
could you try with a Python 3.6 ?

**Comment by mullaengr** [comment]
ok, I will try it.
 Thank you for your time.

**Comment by hamediut** [comment]
Installing MPI v10 worked for me on windows 10

**Comment by gouarin** [comment]
@hamediut thanks for your feedback.

**Comment by gouarin** [comment]
@mullaengr I close this issue.

You can re-open it if you still have installation problems.
