### ISSUE TITLE
Creating Custom Shapes

### ISSUE THREAD

**Issue by sguerin13** [pylbm/pylbm#115]
Hello,

Question, not an issue, If I wanted to create a custom geometry using the base class definition, do I only need to define the init, get_bounds, point_inside, and visualize methods?

- Steve

**Comment by gouarin** [comment]
This is exactly what you need. `visualize` is not mandatory except if you want to plot your shape. You also have to implement the `distance` method.

We will work in the next weeks on the possibility to add a shape built from CAD software and export as .obj, .stl,... files.

**Comment by sguerin13** [comment]
Excellent, Looking forward to it. 

Also, wanted to confirm that the time step dt in the simulation is an absolute time step, not time relative to some other factor. I am planning on sampling the simulation at 30 hz. 

Thanks again,
Steve

**Comment by gouarin** [comment]
yes, the time step is an absolute time step.

I close this issue.

Feel free to reopen it if you have other questions.
