### ISSUE TITLE
[Question] computing drag

### ISSUE THREAD

**Issue by SignificantCell2** [pylbm/pylbm#117]
Hello,
Thank you very much for this amazing library.
I have a question regarding the drag estimation. I can't find any example on how to compute drag on a object using pylbm. Is it possible to compute it?

Thank you

**Comment by gouarin** [comment]
We don't have examples in pylbm to compute drag on an object. But I think if you have the drag coefficient for a given object, it should be fairly easy to compute the drag equation.

**Comment by gouarin** [comment]
@SignificantCell2 I close this issue. You can re-open it if you think it is necessary.
