### ISSUE TITLE
Sympy version

### ISSUE THREAD

**Issue by SignificantCell2** [pylbm/pylbm#118]
Hello,
Is it possible to upgrade the Sympy to the latest version 1.6 ?

Thanks

**Comment by gouarin** [comment]
It's not possible for now to update sympy because we made a hack of codegen module in sympy so our code generator works with pylbm.
But I'm working on it and it should be possible in a few weeks.

**Comment by SignificantCell2** [comment]
Thank you.

**Comment by gouarin** [comment]
pylbm works now with a sympy version >=1.3. (see https://github.com/pylbm/pylbm/pull/134)
