### ISSUE TITLE
3D Aspect Ratio

### ISSUE THREAD

**Issue by gavox** [pylbm/pylbm#125]
Thanks for the good work! I am enjoying this package a lot. 

I've run into an issue with the 3D example of the cube. Basically matplotlib complains about not being able to set the aspect ratio in 3D axes. I've solved it by commenting out lines 481 and 482 in matplotlib_viewer.py. 

This is the outpt I get when I ran the example: 

`NotImplementedError                       Traceback (most recent call last)
~/Documents/03_investigacion/50_camiloLBM/cubo.py in <module>
     16 }
     17 g = pylbm.Geometry(d)
---> 18 g.visualize(viewlabel=True)

~/.local/lib/python3.8/site-packages/pylbm/geometry.py in visualize(self, viewer_app, figsize, viewlabel, fluid_color, viewgrid, alpha)
    297                         )
    298                     ct_lab += 1
--> 299             view.axis(xmin, xmax, ymin, ymax, zmin, zmax, aspect='equal')
    300             view.set_label("X", "Y", "Z")
    301             for elem in self.list_elem:

~/.local/lib/python3.8/site-packages/pylbm/viewer/matplotlib_viewer.py in axis(self, xmin, xmax, ymin, ymax, zmin, zmax, dim, aspect)
    480             self.ax.set_ylim(ymin, ymax)
    481             if aspect is not None:
--> 482                 self.ax.set_aspect(aspect)
    483         else:
    484             self.ax.set_xlim3d(xmin, xmax)

/usr/lib/python3/dist-packages/matplotlib/axes/_base.py in set_aspect(self, aspect, adjustable, anchor, share)
   1278 
   1279         if (not cbook._str_equal(aspect, 'auto')) and self.name == '3d':
-> 1280             raise NotImplementedError(
   1281                 'It is not currently possible to manually set the aspect '
   1282                 'on 3D axes')

NotImplementedError: It is not currently possible to manually set the aspect on 3D axes
`

And then, I commented out the lines: 

`            #if aspect is not None:
            #    self.ax.set_aspect(aspect)
`

Thanks!

**Comment by gouarin** [comment]
Thanks for your message!
I will fix this issue for the next release.

Could you tell us what kind of computation you make with pylbm? We are interested in the usage ;).

**Comment by gavox** [comment]
I have an undergrad student who is learning the basics of the Lattice Boltzmann method, and your project is a good way for him to start.

**Comment by gavox** [comment]
Thanks again for the project. :D

**Comment by gouarin** [comment]
@gavox thanks for the kind words.

Your issue is already fixed in the master branch.
