### ISSUE TITLE
Dynamic Boundary Condition

### ISSUE THREAD

**Issue by maniset** [pylbm/pylbm#127]
Hi,
Thanks for this great library.

I need to change the boundary condition of the Rayleigh-Benard example at different time-steps. Do you have any suggestions?

Thanks

**Comment by gouarin** [comment]
@maniset I added this feature here https://github.com/pylbm/pylbm/pull/132

You can see how it works in the updated example https://github.com/pylbm/pylbm/blob/master/demo/2D/Rayleigh-Benard.py

To have a bottom boundary condition with time dependency, please set the `time_bc` to `True` here https://github.com/pylbm/pylbm/blob/master/demo/2D/Rayleigh-Benard.py#L204

And to modify the boundary condition: https://github.com/pylbm/pylbm/blob/master/demo/2D/Rayleigh-Benard.py#L55-L61

I close this issue but feel free to re-open it if it doesn't work for you as expected.
