### ISSUE TITLE
pylbm conda installation not working with Python 3.8 (Windows)

### ISSUE THREAD

**Issue by ma-sadeghi** [pylbm/pylbm#128]
Basically, it complains that in can't find a compatible mpich. I tried on a fresh virtualenv. I switched back to Python 3.7, and it worked out fine.

**Comment by gouarin** [comment]
I made a new release of pylbm where the sympy dependency is now >=1.3.

This release is available on pip and conda-forge.

Let me know if you have still an issue.

**Comment by ma-sadeghi** [comment]
@gouarin Sorry for the late reply. I tried the new version and it works! Thanks!
