### ISSUE TITLE
pylbm partly outdated?

### ISSUE THREAD

**Issue by mhechthz** [pylbm/pylbm#136]
Hi

I just tried to install pylbm with pythn 3.7. pylbm uninstalled my sympy version and installed sympy 1.1.1 which is rather old. The current version is 1.7.1

Will there be an update?

**Comment by gouarin** [comment]
Hi @mhechthz 

I totally agree with you. I wanted to implement what I have done for codegen into sympy but it takes time.
That is why I decided to put all the work I did into pylbm last week (see https://github.com/pylbm/pylbm/pull/134).
So now the sympy version must be >= 1.3.

I will try to make a release of pylbm next week.

**Comment by mhechthz** [comment]
Perfect. So I will have some patience up to next week.

**Comment by gouarin** [comment]
@mhechthz I made a new release of pylbm that is available on pip and conda-forge.
