### ISSUE TITLE
D3Q19 Domain - Error defining parallelepiped elements

### ISSUE THREAD

**Issue by alejp1998** [pylbm/pylbm#154]
Good afternoon, I have found your LBM library and I am deeply interested to use it to perform some vehicle pollution propagation simulations in urban areas. 

I was trying to define a 3-Dimensional domain for the simulation, using parallelepipeds as elements (acting as the buildings in the urban area). The issue is that the geometry seems to be OK when I visualize it after defining it for the Geometry, doing: 
```
dx = 1.

# Geometry dictionary and box
d = {}
box = {'x': [0,x_size_2km], 'y': [0, y_size_2km], 'z': [0,z_size_500m], 'label': [0,0,0,0,1,0]}
d['box'] = box

# Elements inside box
elements = []

v0,v1 = [dx, 0., 0.], [0., dx, 0.]
for x in range(x_size_2km) :
    for y in range(y_size_2km) :
        if dict_2d[x][y] > 0:
            v2 = [0.,0.,dict_2d[x][y]]
            elem = pylbm.Parallelepiped([x,y,0], v0,v1,v2, label=1)
            elements.append(elem)

d['elements'] = elements

g = pylbm.Geometry(d)
g.visualize()
```

Where the buildings have a fixed x and y size of dx, assigning to v2 its height. Defining the geometry with this code I get the following representation (that matches the expected output). 

![descarga](https://user-images.githubusercontent.com/47430731/121235312-02f19080-c895-11eb-8eac-c41c0d97dfd9.png)

But, if I use these same elements when defining the Domain of the simulation, using the following code, I get an unexpected and non-understandable error:

```
# INPUT 
dico = {}
dico['box'] = box
dico['space_step'] = dx
dico['schemes'] = [{'velocities':list(range(19))}]
dico['elements'] = elements

dom = pylbm.Domain(dico)
```

### OUTPUT ERROR
(array([0., 0., 3.]), array([1., 1., 3.]))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-141b78fa4da0> in <module>
----> 1 dom = pylbm.Domain(dico)

/opt/conda/lib/python3.8/site-packages/pylbm/domain.py in __init__(self, dico, need_validation)
    284         for elem in self.geom.list_elem:
    285             # treat each element of the geometry
--> 286             self.__add_elem(elem)
    287 
    288         log.info(self.__str__())

/opt/conda/lib/python3.8/site-packages/pylbm/domain.py in __add_elem(self, elem)
    546                 # compute the distance and set the boundary label
    547                 # of each cell and the element with the vk velocity
--> 548                 alpha, border = elem.distance(grid, self.dx*vk, 1.)
    549                 # take the indices where the distance is lower than 1
    550                 # between a fluid cell and the border of the element

/opt/conda/lib/python3.8/site-packages/pylbm/elements/cylinder.py in distance(self, grid, v, dmax)
    146         # indices where the intersection is too high or to low
    147         alpha[alpha < 0] = 1.e16
--> 148         ind = np.logical_and(alpha > 0, np.abs(z_cyl + alpha*v_cyl[2]) > 1.)
    149         alpha[ind] = 1.e16
    150         border[ind] = -1.

ValueError: operands could not be broadcast together with shapes (2,2,6) (24,24)

The problem is that I do not understand the cause of this error, and, therefore, I do not know how to fix it. I hope you can help me to fix it, and that the identification of this error is helpful for you.

Thank you in advance, 
Alejandro.

**Comment by bgraille** [comment]
Hi Alejandro,
thank you for your interest.
Your problem is coming when `pylbm` built the domain (in particular the computation of the distance to the bound). I cannot reproduce your problem with my data.
Could you please send to me a small example of your code in order to reproduce the issue ? I can reconstruct the variables x_size_2km and so on but not the dict_2d array...
Regards,
Benjamin.

**Comment by alejp1998** [comment]
Yes, of course, the dictionary "dict_2d" is:
```
dict_2d = {
    0: {0: 6, 1: 6, 2: 6, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    1: {0: 6, 1: 6, 2: 6, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    2: {0: 0, 1: 0, 2: 0, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    3: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 6, 9: 6},
    4: {0: 6, 1: 6, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0},
    5: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0},
    6: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    7: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    8: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    9: {0: 0, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0}
}
```
Where the value 0 means there is no building and the value 6 means there is a building 6 dxs high. Additionally, the size variables are:
```
x_size_2km = 10
y_size_2km = 10
z_size_500m = 10
```

Hope this is enough for you to reproduce the issue.

Thanks, 
Alejandro.

**Comment by bgraille** [comment]
Thank you again for opening this issue. It was a bug when the distance to the bounds was computed.
I test your configuration and for me the bug is now fixed.
You probably have to download the last version of `pylbm`: if you are interested to use `pylbm`, it is probably interessant for you to clone the repository in order to follow the last developments.
Regards
B.

```python
import pylbm

dx = 1.
x_size_2km = 10
y_size_2km = 10
z_size_500m = 10

dict_2d = {
    0: {0: 6, 1: 6, 2: 6, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    1: {0: 6, 1: 6, 2: 6, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    2: {0: 0, 1: 0, 2: 0, 3: 6, 4: 0, 5: 0, 6: 6, 7: 6, 8: 6, 9: 6},
    3: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 6, 9: 6},
    4: {0: 6, 1: 6, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0},
    5: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0},
    6: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    7: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    8: {0: 6, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0},
    9: {0: 0, 1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 0, 8: 0, 9: 0}
}

# Geometry dictionary and box

d = {}
box = {
    'x': [0, x_size_2km],
    'y': [0, y_size_2km],
    'z': [0, z_size_500m],
    'label': [0, 0, 0, 0, 1, 0]
}
d['box'] = box

# Elements inside box

elements = []

v0, v1 = [dx, 0., 0.], [0., dx, 0.]
for x in range(x_size_2km):
    for y in range(y_size_2km):
        if dict_2d[x][y] > 0:
            v2 = [0., 0., dict_2d[x][y]]
            elem = pylbm.Parallelepiped(
                [x, y, 0], v0, v1, v2, label=2
            )
            elements.append(elem)

d['elements'] = elements

g = pylbm.Geometry(d)
# g.visualize()

d['space_step'] = dx
d['schemes'] = [{'velocities': list(range(19))}]

dom = pylbm.Domain(d)
print(dom)
dom.visualize(
    view_distance=False,
    view_in=False,
    view_out=False,
    view_bound=True,
    view_geom=True,
    label=[2]
)
```

**Comment by alejp1998** [comment]
Thank you for answering and solving it so fast. I will keep on using the library, as well as informing you if I find any more issues.

Regards, 
Alejandro.
