### ISSUE TITLE
How to run the files in demo folder

### ISSUE THREAD

**Issue by pnvdp** [pylbm/pylbm#164]
python3 advection.py
Traceback (most recent call last):
  File "/home/nandita/Downloads/pylbm/demo/1D/advection.py", line 19, in <module>
    import pylbm
  File "/home/nandita/anaconda3/envs/pylbm_env/lib/python3.10/site-packages/pylbm-0.8.0-py3.10.egg/pylbm/__init__.py", line 13, in <module>
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

**Comment by gouarin** [comment]
You need MPI library installed on your OS but if you are on linux as it seems to be, when you install pylbm, mpich should be installed with mpi4py.

Could you check that mpi4py and mpich or openmpi are well installed in your pylbm_env using the command line
`conda list`?

**Comment by pnvdp** [comment]
I have checked. They are already installed. May be I think I am in wrong folder. To import pylbm, do it need the int.py file?

**Comment by pnvdp** [comment]
(base) nandita@nandita:~/Downloads/pylbm/demo/1D$ python3 advection.py
Traceback (most recent call last):
  File "/home/nandita/Downloads/pylbm/demo/1D/advection.py", line 19, in <module>
    import pylbm
ModuleNotFoundError: No module named 'pylbm'
(base) nandita@nandita:~/Downloads/pylbm/demo/1D$ 

When I am running with conda activated, it is showing the above error. Previously I was doing it with pylbm_envs activated.

**Comment by gouarin** [comment]
First, you have to activate the conda environment where pylbm was installed. 

```
conda activate pylbm_env
```

And then run the example with

```
python advection.py
```

Once the environment is activated, you can check if pylbm is a known module by trying to import it into a Python interpreter.

**Comment by pnvdp** [comment]
I did the same as you suggested but same error is coming means pylbm itself not installed.
![Screenshot from 2022-04-21 14-16-02](https://user-images.githubusercontent.com/58776691/164417029-11d602f9-6b0e-4d9a-8b2a-0d2fcaa72f02.png)

**Comment by pnvdp** [comment]
My problem is solved. Thanks.
