### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by irwanad** [pylbm/pylbm#27]
compilation terminated.
    failure.
    removing: _configtest.c _configtest.o
    error: Cannot compile MPI programs. Check your configuration!!!
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2GJvNr/mpi4py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4aP939-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2GJvNr/mpi4py

**Comment by gouarin** [comment]
@irwanad could you give us more informations of how you tried to install pyLBM ? And on which OS ?

It seems that the installation of `mpi4py` failed.

**Comment by irwanad** [comment]
I have solved above issue, but now im facing another problem when i do the installation i got this message
======================================================
Installed /usr/local/lib/python2.7/dist-packages/pyLBM-0.2.1-py2.7.egg
Processing dependencies for pyLBM==0.2.1
Searching for pyevtk>=1.0.0
Reading hg+https://bitbucket.org/pauloh/pyevtk
Download error on hg+https://bitbucket.org/pauloh/pyevtk: unknown url type: hg+https -- Some packages may not be found!
Reading https://pypi.python.org/simple/pyevtk/
Best match: pyevtk 1.1.0
Downloading https://pypi.python.org/packages/62/49/0b4ff2cef568825d6a01a2f05e3287f46e4350fb8f7931ccd3d784414b3a/pyevtk-1.1.0.tar.gz#md5=2ae1a98ddbfc51a48996cb680caa2957
Processing pyevtk-1.1.0.tar.gz
Writing /tmp/easy_install-GNz4DN/pyevtk-1.1.0/setup.cfg
Running pyevtk-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GNz4DN/pyevtk-1.1.0/egg-dist-tmp-2f57ld
error: [Errno 2] No such file or directory: 'README.md'

**Comment by gouarin** [comment]
Could you install mercurial before ?

If you use conda

`conda install mercurial`

**Comment by irwanad** [comment]
I've already install mercurial but the error still the same

**Comment by gouarin** [comment]
Could you try with the source code ?

`git clone https://github.com/pylbm/pylbm.git`

`pip install -r requirements.txt`

`pip install .`

and let me know if you have still this issue.

The packaging of pylbm is not well defined and I will work on this in the next weeks.

**Comment by irwanad** [comment]
what is the content of requirements.txt ?

**Comment by gouarin** [comment]
It's the dependencies of pylbm.

**Comment by gouarin** [comment]
@irwanad you can now install cleanly pylbm using the following command

```
conda install pylbm -c pylbm -c conda-forge
```
