### ISSUE TITLE
BouzidiBounceBack vs. Bouzidi_bounce_back, etc.

### ISSUE THREAD

**Issue by billpage** [pylbm/pylbm#70]
https://github.com/pylbm/pylbm/blob/ff71d6aa68839d92af266578a791308334dd660b/demo/2D/Karman_vortex_street.py#L100

The demo files use generator names that are inconsistent with

https://github.com/pylbm/pylbm/blob/6217e6f72acb20fbab04ac702b9a1bdd119cfd73/pylbm/boundary.py#L467

from commit

https://github.com/pylbm/pylbm/commit/ff71d6aa68839d92af266578a791308334dd660b

**Comment by gouarin** [comment]
`Bouzidi_bounce_back` is the name of the generated function and `BouzidiBounceBack`is the class which implements the Bouzidi bounce back condition and generates the associated code. That means that they are not related and the first one is for intern tasks.

**Comment by billpage** [comment]
But I get an error when running the demo code that says that BouzidiBounceBack is not defined.

**Comment by gouarin** [comment]
How did you install pylbm ? If you used conda or pip then the examples in Master are not good. 

We have implemented a lot of new features during these last months and we will provide a new release soon.

The old examples are here
https://github.com/pylbm/pylbm/archive/0.3.2.tar.gz

**Comment by billpage** [comment]
I used pip and tried the Von Karman demo from readthedocs and got an error (not this one). Then I started digging and got confused.  Now if I run the same demo from the 0.3.2 archive I get a different error:

> TypeError: The first argument must be a sympy symbol.

but that looks like something completely different.  Would you recommend that I install directly from the repository instead?

**Comment by gouarin** [comment]
Could you chat on the gitter channel https://gitter.im/pylbm/pylbm ? It will be easier to explain how to install pylbm.
