### ISSUE TITLE
Tutorial problem?

### ISSUE THREAD

**Issue by kdfluxit** [pylbm/pylbm#86]
I'm very interested in your project--pylbm, it is excellent. But recently, I have a problem with the tutorial case:
when I try to run the tutorial .py
https://github.com/pylbm/pylbm_gallery/blob/master/2D/Karman_vortex_street/Re%3D2500/Karman_vortex_street.py

An error occurs

Could u please give me some suggestion?
Thank you

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-18377c36a698> in <module>
    114 }
    115 
--> 116 sol = pyLBM.Simulation(dico)
    117 
    118 Re = rhoo*uo*2*radius/mu

/usr/local/lib/python3.7/site-packages/pylbm-0.3.2-py3.7.egg/pylbm/simulation.py in __init__(self, dico, domain, scheme, sorder, dtype, check_inverse)
    211             self._Fold.set_conserved_moments(self.scheme.consm, self.domain.stencil.nv_ptr)
    212 
--> 213         self.scheme.generate(self.generator, sorder, self.domain.valin)
    214 
    215         self.log.info('Build boundary conditions')

/usr/local/lib/python3.7/site-packages/pylbm-0.3.2-py3.7.egg/pylbm/scheme.py in generate(self, backend, sorder, valin)
    792 
    793         # add the function f2m as m = M f
--> 794         generator.add_routine(('f2m', For(iloop, Eq(m, M*f))), settings={"prefetch":[f[0]]})
    795         # add the function m2f as f = M^(-1) m
    796         generator.add_routine(('m2f', For(iloop, Eq(f, invM*m))), settings={"prefetch":[m[0]]})

/usr/local/lib/python3.7/site-packages/pylbm-0.3.2-py3.7.egg/pylbm/generator/generator.py in add_routine(self, name_expr, argument_sequence, local_vars, settings)
     10 
     11     def add_routine(self, name_expr, argument_sequence=None, local_vars=None, settings={}):
---> 12         self.routines[name_expr[0]] = make_routine(name_expr, argument_sequence, local_vars, settings)[0]
     13 
     14     def compile(self, backend="cython", verbose=False):

/usr/local/lib/python3.7/site-packages/pylbm-0.3.2-py3.7.egg/pylbm/generator/codegen.py in make_routine(name_expr, argument_sequence, local_vars, settings)
    695     for name, expr in name_expr:
    696         routines.append(LBMCodeGen().routine(name, expr, argument_sequence,
--> 697                                              local_vars, settings))
    698 
    699     return routines

/usr/local/lib/python3.7/site-packages/pylbm-0.3.2-py3.7.egg/pylbm/generator/codegen.py in routine(self, name, expr, argument_sequence, local_vars, settings)
    258                 metadata = {}
    259 
--> 260             arg_list.append(InputArgument(symbol, **metadata))
    261 
    262         output_args.sort(key=lambda x: str(x.name))

/usr/local/lib/python3.7/site-packages/sympy/utilities/codegen.py in __init__(self, name, datatype, dimensions, precision)
    291         """
    292         if not isinstance(name, (Symbol, MatrixSymbol)):
--> 293             raise TypeError("The first argument must be a sympy symbol.")
    294         if datatype is None:
    295             datatype = get_default_datatype(name)

TypeError: The first argument must be a sympy symbol.

**Comment by gouarin** [comment]
@kdfluxit thanks for your interest about pylbm !

I presume you use the master branch. We made a lot of improvement in the master branch and we hope to make the release 0.4 soon.
But we don't have made the modifications in the pylbm gallery with the new features yet.

If you want to understand how works the master version, you should take a look at our demo directory into the pylbm repo.

I will update the gallery before the end of this week.

**Comment by kdfluxit** [comment]
> @kdfluxit thanks for your interest about pylbm !
> 
> I presume you use the master branch. We made a lot of improvement in the master branch and we hope to make the release 0.4 soon.
> But we don't have made the modifications in the pylbm gallery with the new features yet.
> 
> If you want to understand how works the master version, you should take a look at our demo directory into the pylbm repo.
> 
> I will update the gallery before the end of this week.

Thank you!

**Comment by gouarin** [comment]
@kdfluxit sorry for the delay. The examples in the gallery repo are now up to date!
